name    'nm-locales'
version '1.0.0'
author  'Javier Bertoli'
license 'Apache2'
project_page 'http://www.netmanagers.com'
source  'https://github.com/netmanagers/puppet-locales'
summary 'Puppet module for locales'
description 'This module installs and manages locales. Check README for details.'
dependency 'example42/puppi', '>= 2.0.0'
# dependency 'example42/monitor', '>= 2.0.0'
# dependency 'example42/firewall', '>= 2.0.0'
